publishDir = "docs"
baseURL = "https://NolanZhuang.github.io/VRBlogs/"
title = "Binario"
languageCode = "en-us"
paginate = 10
theme = "binario"

[Params]
  description = "Responsive card-based & code-light Hugo theme"
  columns = 2
